### ISSUE TITLE
Add a config option to specify output directory

### ISSUE THREAD

**Issue by sgwebmaster** [ben-rogerson/laravel-mix-twig-to-html#4]
currently the output directory can't be set using the config object. It would be a lot useful if we can configure the output directory to something like `dist`.

**Comment by ben-rogerson** [comment]
hey there!

The output directory is specified with mix.
You can specify the output directory in your mix config like this:

```js
// webpack.mix.js

mix.setPublicPath("dist")

require("laravel-mix-twig-to-html")
mix.twigToHtml({
    ...
})
```

If you're after a build setup (or better examples of how you can use this mix plugin) perhaps take a look at my [agency webpack mix config](https://github.com/ben-rogerson/agency-webpack-mix-config).
