### ISSUE TITLE
Processing twig files as they are added

### ISSUE THREAD

**Issue by eurolife** [ben-rogerson/laravel-mix-twig-to-html#7]
Hi and thanks for this very useful plugin.

I'm running the npm watch command and I noticed that it automatically will process the twig files to html only if they already exist before I start the watch command. If I add new ones, it doesn't see them and doesn't process them unless I stop the watch command and then re-run it. Is there a way to configure it to watch for new files? I hope this makes sense. Thanks in advance for your help.

**Comment by ben-rogerson** [comment]
There's no built-in active watcher. I use other packages like [nodemon](https://www.npmjs.com/package/nodemon) for this type of thing.
